TryGhost/knex-migrator

package.json

This makes the migrator actually function when installed globally :smile:

Add missing lodash dependency

---

lib/errors.js

refs #13
- add hint how to install knex-migrator
- add the repo url
```
[2016-11-01 11:55:22] ERROR
Please run knex-migrator init
level:normal
If knex-migrator is not installed, please run "npm install -g knex-migrator"
Read more here: https://github.com/TryGhost/knex-migrator
```
@ErisDS If you would like to change the description or add something, just tell me 👍

🎨  add help for DatabaseIsNotOkError error

---

lib/index.js
test/assets/.knex-migrator
test/functional_spec.js

no issue
- "init" > "1.0" is true and it can happen that the "init" folder get's ignored when making an integrity check
- add more tests for versionings
- ensure we compare numbers for versions

🐛  current version behaviour

---

lib/database.js

closes #22
- enclose database name in backtics (`) to escape any special characters
- add IF NOT EXISTS clause to db creation statement

Escape db name in database creation

---

lib/index.js
test/functional_spec.js

🐛  return correct error codes when looking up the migrations table

---

lib/database.js

When passing through the normal knex connection parameters, the database.connection function now uses the values passed in and defaults to the hardcoded options. This allows greater flexibility of database charsets and timezones.

Enable charset and timezone to be set via MigratorConfig.js

---

logging.js

refs https://github.com/TryGhost/Ignition/issues/3
- if using knex-migrator within the application, knex-migrator used the config file from the root directory
- this caused bunyan to create another pair of log files if file transport is defined
- make logging properties static, because logging is only useful when using the CLI
- and the CLI will always log to stdout for now

🎨  static logging properties

---

README.md
bin/knex-migrator-health
bin/knex-migrator-init
bin/knex-migrator-migrate
bin/knex-migrator-reset
lib/index.js
test/functional1_spec.js

no issue
This PR is reasoned by a use case for our [CLI](https://github.com/TryGhost/Ghost-CLI) tool.
It adds a new option to the migrate command. By this the CLI does not have to run two shell commands (init and migrate). The error handling via the shell is harder than pragmatically.
e.g.
`NODE_ENV=production knex-migrator migrate --init --mgpath current/`

migrate --init, bug fixes and --mgpath option

---

lib/index.js

no issue
- add a clearer warning message
- if you force running a future migration version, knex-migrator detects that now and doesn't show the warning

🐛  Fix future migration versions

---

lib/index.js

This is a small change to ensure that the error code "DB_NEEDS_MIGRATION" isn't thrown when there are too many migrations already.
This can cause us to retry migrations, when actually a manual fix is required.
This doesn't do anything to resolve the problem of duplicates occurring in the first place.
refs #76 
- If there are more actual migrations than expected migrations, throw a different error
- This prevents us from showing "Migrations are missing" when the DB health check fails due
to duplicate / too many migrations

Add error handling for duplicate migrations

---

.gitignore
README.md
config.testing.json
package.json
test/functional_spec.js
test/utils.js

no issue
- sqlite3 stays default for now
- be able to run `NODE_ENV=testing-mysql npm test`
- @TODO: run tests with MySQL in Travis by default

Make it possible to run tests with a different database e.g. MySQL

---

README.md
lib/index.js

**In short** <br> This adds the new `knexMigratorConfig` field into the JS API:
```js
const knexMigrator = new KnexMigrator({
knexMigratorConfig: {
database: {...},
migrationPath: '',
currentVersion: '',
subfolder: '',
},
});
```
When present, this field takes the precedence over `knexMigratorFilePath`.
**Reasoning** <br> I use knex-migrator from JS to initialize different Ghost DBs on runtime:
```js
const fillDbWithData = async (dbName, username, password) => {
process.env.database__client = 'mysql';
process.env.database__connection__host = process.env.DB_HOST;
process.env.database__connection__user = username;
process.env.database__connection__password = password;
process.env.database__connection__database = dbName;
const knexMigrator = new KnexMigrator({
knexMigratorFilePath: …
```

Add support for specifying the config via options

---

lib/utils.js
package.json
test/utils_spec.js

The utils function isGreaterThanVersion was causing the following case:
1.10.0 would be classified as greater than 2.0.0. This was because
both would be stripped of their full stops (periods) and converted into
numbers. Resulting in a comparison of 1100 (1.10.0) against 200.
The compare-ver library has been introduced to handle semver like
comparisons.
Closes #97

Correct version number comparison

---

lib/index.js
package.json
test/functional/database_spec.js
test/functional/functional_spec.js
test/functional/implicit_commits_spec.js
test/functional/rollback_1_spec.js
test/functional/rollback_2_spec.js
test/functional/rollback_3_spec.js
test/functional/rollback_4_spec.js
test/unit/_rollback_spec.js

no issue
- do not rollback all tasks of a version
- e.g.
- version 2.0 has 4 scripts
- it failed in the second script
- we don't have to rollback all 4 scripts
- only the second and the first
- only rollback the second if it wasn't running in a transaction

Optimised rollback task

---

lib/errors.js
lib/index.js
test/unit/_rollback_spec.js

no issue
- some migrations that drop tables which include data will mean that even though the `down` task could re-create the database schema it's still of no use when the data is missing
- adds support for specifying this in tasks' config with `module.exports.config = {irreversible: true}`
- if an irreversible migration is included in a rollback task list then an error will be thrown immediately with no tasks being run
TODO:

Added support for "Irreversible migrations"

---

lib/utils.js

- closes #174
Tested by adding a dotfile to `test` directory, run tests (mostly fail), make change, re-run test & they pass.

Ignored dotfiles in versions folder

---

lib/database.js

On MySQL 8, the default collation changed from `utf8mb4_general_ci` to `utf8mb4_0900_ai_ci`, and Node's MySQL driver doesn't support the new collation (see [here](https://github.com/TryGhost/Ghost/issues/11625#issuecomment-644879046) for more context). As such, this is updating the create database query to explicitly specify the collation, in order to support running Ghost w/MySQL 8.

Added collation to create table statement

---

migrations/add-primary-key-to-lock-table.js
migrations/index.js
migrations/lock-table.js
test/functional/functional_spec.js

issue https://github.com/TryGhost/Team/issues/267
Tables without primary keys cause issues with MySQL replication & clustering.

💡 Changed the lock_key column constraint to primary key

---

migrations/add-primary-key-to-lock-table.js

pr https://github.com/TryGhost/Ghost/pull/12739
These queries could be slow when there are a lot of tables/databases, so it's better to avoid them. MySQL provides a good error when failing to add a primary key too.

Removed queries against mysql information_schema

---

lib/index.js
lib/utils.js

no issue
- throughout the code, there are several places where we call our
`readTasks` function to return a list of migrations in a folder
- this function gets all the files in a dir and requires them so it can
populate an object with the up/down functions and the config
- we don't need this information in some places because we're often just
using the names of the migrations, or counting how many migrations there are
- this commit extracts the code to get a list of files into a
`listFiles` function, which simply lists the files (and excludes dot
directories) - this is then used within `readTasks`
- this also switches the places in our code, that was calling `readTasks` but
didn't need the migration functions or config, to `listFiles`
- in Ghost this saves about 5% of the on-stack time …

Optimized code for listing migrations

---

.github/workflows/test.yml

refs https://github.com/TryGhost/Ghost/blob/main/package.json#L49
- this commit bumps the Node versions used in CI to the minimum
supported by Ghost

Updated CI Node versions

---

lib/index.js

refs https://github.com/TryGhost/knex-migrator/issues/252
- the referenced issue describes performance problems with the integrity check code in knex-migrator
- this commit solves half of the problem - 1 DB call per migration minor version folder
- this results in 70+ (and growing!) DB calls at boot, with each one going back and forth to the DB... not efficient
- what the code actually needed was a count of how many migrations are currently in the DB, group by minor version - this is very easy to do in SQL and therefore knex
- this commit switches the code around to group all the DB migrations first, and then compares against the folders locally
- this results in a drop of SQL queries from 70+ to 1 🚀

⚡ Optimized performance of integrity check DB calls

---

migrations/add-primary-key-to-lock-table.js
package.json
yarn.lock

refs https://github.com/TryGhost/Toolbox/issues/213
- this commit switches to using `@tryghost/database-info` so we can
remove some of the specific `"sqlite3"` string checks ahead of moving
to `better-sqlite3`

Removed `sqlite3`-specific string checks

---

lib/database.js
package.json
test/functional/functional_spec.js
yarn.lock

refs https://github.com/TryGhost/Toolbox/issues/213
- these checks can be abstracted out to the database-info utility and
save us checking the strings in different places

Switched internal database checks to helper utility

---

lib/database.js

- I'm not sure why we're checking IDs here, I presume it's just from
before knex had built-in utilities
- this commit switches to checking the table via the built-in utility
instead of checking IDs

Refactored migrations table creation to use helper

---

lib/database.js
package.json
test/functional/implicit_commits_spec.js
yarn.lock

refs https://github.com/TryGhost/Toolbox/issues/213
- I originally tried to keep `knex-migrator` running with `sqlite3` by
monkey-patching the driver into the dialect but this is causing more
issues in Ghost
- this commit switches to the actual SQLite driver supported by the
sqlite client in knex

Switched from `sqlite3` to `@vscode/sqlite3`

---

package.json

ref https://github.com/TryGhost/knex-migrator/commit/4571d5433f29a31f37bdeef47d7003ce6c903546
- The file list in package.json was missed when the filename got changed from logging to loggingrc
- This changes it so that npm knows what files should be in the package

Fixed filename changed to loggingrc
